### ISSUE TITLE
Uncaught TYPO3 Exception: Call to undefined method ContentObjectRenderer::createUrl()

### ISSUE THREAD

**Issue by Pravin0711** [ErHaWeb/klaro_consent_manager#6]
I am using TYPO3 11.5.31 and Klaro 1.7.1

After install Klaro extension and select Klaro configuration in Site Configuration my website is down. i see below error. 

`Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::createUrl() | Error thrown in file ../typo3conf/ext/klaro_consent_manager/Classes/Service/KlaroService.php in line 804.`

I think you need to use function  **typoLink_URL()** instead of **createUrl()**

**Comment by ErHaWeb** [comment]
Many thanks for the report and the suggested solution. I will have a look at it soon.
