### ISSUE TITLE
Cannot assign null to property ErHaWeb\KlaroConsentManager\Service\KlaroService::$siteLanguage of type TYPO3\CMS\Core\Site\Entity\SiteLanguage

### ISSUE THREAD

**Issue by milk-horizon** [ErHaWeb/klaro_consent_manager#8]
TypeError typovv12.4.14
Cannot assign null to property ErHaWeb\KlaroConsentManager\Service\KlaroService::$siteLanguage of type TYPO3\CMS\Core\Site\Entity\SiteLanguage

**Comment by ErHaWeb** [comment]
Thanks for the report. Could you please provide the full stack trace and, if possible, more information about the context in which this error occurs?

**Comment by milk-horizon** [comment]
$this->siteLanguage = $request->getAttribute('language') return null
